/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marvel-logo-ffb798fdd2674e6fa17d812b78708064
Title: Marvel Logo
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Marvellogo(props) {
  const { nodes, materials } = useGLTF('/models/Marvellogo-transformed.glb')
  const modelRef = useRef();
  useFrame((state) => {
      if (modelRef.current) {
        modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime); // Rotates on Y-axis
      }
    });
  return (
    <group {...props} ref={modelRef} scale={[0.029, 0.010, 0.019]} rotation={[0.1, 0, 0]} position={[-4.9, 4.7, 0]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Logo_02_-_Default_0'].geometry}
        material={materials['02_-_Default']}
      />
    </group>
  )
}

useGLTF.preload('/models/Marvellogo-transformed.glb')